<?php
/* @var block \Magebees\Finder\Block\Finder */
if ($block->getEnabled()) :
$_helper = $this->helper('Magebees\Finder\Helper\Data');
$finderId = $block->getData('finder_id');
$search = 0;
$path = $this->getRequest()->getRequestString();
$search = strpos($path, 'finder');
if (!$finderId) {
    $finderId = $_helper->getFinderId($path);
}

$this->setFinderId($finderId);
$finders = $block->getFinderById($finderId);

$urlstring = $finders->getYmmValueFromPath($path);

$current  = $finders->getSavedValue('current');
if ($urlstring!=$current) {
    $dropdowns = $finders->getDropdownsByCurrent($urlstring);
    $finders->saveDropDownValues($dropdowns);
}
$finderDropdowns = $block->getDropdownsCollectionByFinderId($finderId);
$dropdowncounts=$finderDropdowns->count();
$dropdown_id = $finderDropdowns->getFirstItem()->getData('dropdown_id');

if ($finders->getStatus() && count($finderDropdowns)!="") { ?>
<?php if ($block->getLayout()->getUpdate()->getPageLayout() === '2columns-left')  : ?>
<div class="finderProducts vertical">
    <?php else : ?>
    <div class="finderProducts horizontal">
        <?php endif  ?>
        <form action="<?php echo $this->getSearchResultUrl(); ?>" id="finderform_<?php echo $finderId ?>" name="finderform"  class="finderform" method="post">
            <input type="hidden" name="finder_id" value="<?php echo $finderId ?>">
            <h4 class="finder_header"><?php echo __($finders->getTitle()); ?></h4>
            <div id="<?php echo "finderDropdowns_".$finderId ?>" class="finderDropdowns">
                <ul>
                    <?php $i=1;?>
                    <?php foreach ($finderDropdowns as $dropdown) : ?>
                    <li id="drop_<?php echo $finderId ?>_<?php echo $i?>" class="drop_<?php echo $i; ?> column<?php echo $finders->getNoOfColumns() ?>">

                        <select name="finder[<?php echo $dropdown->getId() ?>]" id="finder_<?php echo $finderId ?>_<?php echo $dropdown->getId() ?>" drop-down-counts="<?php echo $dropdowncounts ?>" drop-down-id="<?php echo $dropdown->getId() ?>" >

                            <?php foreach ($block->getDropdownValues($dropdown) as $val) : ?>
                                <?php if ( $val['value']==0) : ?>
                                    <option value="0" selected="selected" >Please  Select  <?php echo __($dropdown->getName()); ?></option>
                                <?php endif ?>>

                                <option value="<?php echo $val['value'] ?>"
                                    <?php if ($val['selected']) : ?>
                                        selected="selected"
                                    <?php endif ?>>
                                    <?php echo $val['label'] ?>
                                </option>
                            <?php endforeach ?>
                        </select>
                        <?php endforeach; ?>
                </ul>
            </div>
            <button id="find_<?php echo $finderId ?>" type="submit" title="Find" value="1" name="find" class="action subscribe primary" <?php if (!$block->isButtonEnabled()) :
            ?>disabled=""<?php
            endif; ?>  ><span><?php echo __($block->getFindBtnText()) ?></span></button>
            <button id="reset_<?php echo $finderId ?>" drop-down-counts="<?php echo $dropdowncounts ?>" name="reset" value="1" title="Reset" class="button" <?php if ($search) :
                ?> type="submit" <?php
            else :
                ?> type="button" <?php
            endif; ?> ><span><span><?php echo __($block->getResetBtnText()) ?></span></span></button>
        </form>
    </div>
    <?php
    }
    ?>
    <script type="text/javascript">
        requirejs(['jquery','cwsfinder'], function(jQuery){
            var finderMage = {'finderId':'<?php echo $finderId ?>','optionurl':'<?php echo $block->getOptionValueUrl() ?>','searchurl':'<?php echo $block->getSearchResultUrl() ?>','dropdowncounts':<?php echo $dropdowncounts ?>,'autosearch':<?php echo $block->getAutosearch() ?>};
            var dropdown_div_id = '<?php echo "#finderDropdowns_".$finderId ?>';
            jQuery(dropdown_div_id).cwsfinder(finderMage);
        });
    </script>
    <?php endif; ?>
