<style>
    #page-preloader {
        position: fixed;
        left: 0;
        top: 0;
        right: 0;
        bottom: 0;
        z-index: 9999;
    }
    @media print {
        #page-preloader{
            display: none;
        }
    }
    body .loading-mask .loader img,
    body .loading-mask .loader p{
        display: none;
    }

    #page-preloader .spinner,
    body .loading-mask .loader{
        position: absolute;
        z-index: 9999;
        left: 50%;
        top: 50%;
        margin: -32px 0 0 -22px;
        width: 49px;
        height: 49px;
        line-height: 90px;
        box-sizing: border-box;
        text-align: center;
        text-transform: uppercase;
        -o-text-transform: uppercase;
        -ms-text-transform: uppercase;
        -webkit-text-transform: uppercase;
        -moz-text-transform: uppercase;
    }

    #page-preloader .spinner:before,
    body .loading-mask .loader:before {
        content: '';
        width: 49px;
        height: 5px;
        background: rgb(0,0,0);
        opacity: 0.1;
        position: absolute;
        top: 58px;
        left: 0;
        border-radius: 50%;
        animation: shadow 0.58s linear infinite;
        -o-animation: shadow 0.58s linear infinite;
        -ms-animation: shadow 0.58s linear infinite;
        -webkit-animation: shadow 0.58s linear infinite;
        -moz-animation: shadow 0.58s linear infinite;
    }

    #page-preloader .spinner:after,
    body .loading-mask .loader:after {
        content: '';
        width: 49px;
        height: 49px;
        background: rgb(255,60,0);
        position: absolute;
        top: 0;
        left: 0;
        border-radius: 3px;
        animation: cssload-animate 0.58s linear infinite;
        -o-animation: cssload-animate 0.58s linear infinite;
        -ms-animation: cssload-animate 0.58s linear infinite;
        -webkit-animation: cssload-animate 0.58s linear infinite;
        -moz-animation: cssload-animate 0.58s linear infinite;
    }

    @keyframes cssload-animate {
        17% {
            border-bottom-right-radius: 3px;
        }
        25% {
            transform: translateY(9px) rotate(22.5deg);
        }
        50% {
            transform: translateY(18px) scale(1, 0.9) rotate(45deg);
            border-bottom-right-radius: 39px;
        }
        75% {
            transform: translateY(9px) rotate(67.5deg);
        }
        100% {
            transform: translateY(0) rotate(90deg);
        }
    }

    @-o-keyframes cssload-animate {
        17% {
            border-bottom-right-radius: 3px;
        }
        25% {
            -o-transform: translateY(9px) rotate(22.5deg);
        }
        50% {
            -o-transform: translateY(18px) scale(1, 0.9) rotate(45deg);
            border-bottom-right-radius: 39px;
        }
        75% {
            -o-transform: translateY(9px) rotate(67.5deg);
        }
        100% {
            -o-transform: translateY(0) rotate(90deg);
        }
    }

    @-ms-keyframes cssload-animate {
        17% {
            border-bottom-right-radius: 3px;
        }
        25% {
            -ms-transform: translateY(9px) rotate(22.5deg);
        }
        50% {
            -ms-transform: translateY(18px) scale(1, 0.9) rotate(45deg);
            border-bottom-right-radius: 39px;
        }
        75% {
            -ms-transform: translateY(9px) rotate(67.5deg);
        }
        100% {
            -ms-transform: translateY(0) rotate(90deg);
        }
    }

    @-webkit-keyframes cssload-animate {
        17% {
            border-bottom-right-radius: 3px;
        }
        25% {
            -webkit-transform: translateY(9px) rotate(22.5deg);
        }
        50% {
            -webkit-transform: translateY(18px) scale(1, 0.9) rotate(45deg);
            border-bottom-right-radius: 39px;
        }
        75% {
            -webkit-transform: translateY(9px) rotate(67.5deg);
        }
        100% {
            -webkit-transform: translateY(0) rotate(90deg);
        }
    }

    @-moz-keyframes cssload-animate {
        17% {
            border-bottom-right-radius: 3px;
        }
        25% {
            -moz-transform: translateY(9px) rotate(22.5deg);
        }
        50% {
            -moz-transform: translateY(18px) scale(1, 0.9) rotate(45deg);
            border-bottom-right-radius: 39px;
        }
        75% {
            -moz-transform: translateY(9px) rotate(67.5deg);
        }
        100% {
            -moz-transform: translateY(0) rotate(90deg);
        }
    }

    @keyframes shadow {
        0%,
        100% {
            transform: scale(1, 1);
        }
        50% {
            transform: scale(1.2, 1);
        }
    }

    @-o-keyframes shadow {
        0%,
        100% {
            -o-transform: scale(1, 1);
        }
        50% {
            -o-transform: scale(1.2, 1);
        }
    }

    @-ms-keyframes shadow {
        0%,
        100% {
            -ms-transform: scale(1, 1);
        }
        50% {
            -ms-transform: scale(1.2, 1);
        }
    }

    @-webkit-keyframes shadow {
        0%,
        100% {
            -webkit-transform: scale(1, 1);
        }
        50% {
            -webkit-transform: scale(1.2, 1);
        }
    }

    @-moz-keyframes shadow {
        0%,
        100% {
            -moz-transform: scale(1, 1);
        }
        50% {
            -moz-transform: scale(1.2, 1);
        }
    }
</style>

<script type="text/javascript">
    window.onload = function() {

        function fadeOut(el){
            el.style.opacity = 1;

            var last;
            var tick = function() {
                el.style.opacity = +el.style.opacity - (new Date() - last) / 600;
                last = +new Date();

                if (+el.style.opacity > 0) {
                    (window.requestAnimationFrame && requestAnimationFrame(tick)) || setTimeout(tick, 100);
                } else{
                    el.style.display = "none";
                }
            };
            tick();
        }

        var pagePreloaderId = document.getElementById("page-preloader");
        setTimeout(
            function () {
                fadeOut(pagePreloaderId)
            }, 1000);
    };
</script>

<div id="page-preloader">
    <div class="spinner"></div>
</div>